Add table to DB tournament_registration.
ridisi95/gulag pull request #8
Opened 2021-01-21 17:11 UTC by RideSVEL

Some test case API endpoint you can get by postman collection link: 
https://www.postman.com/collections/36d0e96c05187528eee7

2021-01-23 11:33 UTC, ridisi95 commented on src/main/java/com/gulag/entity/Tournament.java
> +public class Tournament {
Add @FieldDefaults(level = AccessLevel.PRIVATE) instead of using "private" modifier for all variables

2021-01-23 14:29 UTC, ridisi95 requested changes

2021-01-24 15:54 UTC, ridisi95 requested changes

2021-01-24 15:54 UTC, ridisi95 commented on src/main/java/com/gulag/services/UserDtoService.java
> +    @Autowired
You don't need to use @Autowired when you use @RequiredArgsConstructor.
You can check this https://www.baeldung.com/spring-injection-lombok

2021-01-24 15:54 UTC, ridisi95 commented on src/main/java/com/gulag/mapper/TournamentRegistrationDtoMapper.java
> +    TournamentRegistrationDto tournamentRegistrationTournamentRegistrationDto(
Perhaps we can use some shorter name as mapEntityToDTO.

2021-01-24 15:54 UTC, ridisi95 commented on src/main/java/com/gulag/services/UserDtoService.java
> +        }
In my opinion it looks better if you use mapper method for object list

2021-01-24 15:54 UTC, ridisi95 commented on src/main/java/com/gulag/services/TournamentRegistrationService.java
> +    TournamentRegistrationRepository tour;
Rename it please. e.g. tourRegRepository

2021-01-24 15:54 UTC, ridisi95 commented on src/main/resources/migrations/V3__T14.sql
> +
Generally, you are correct. but we have only 2 columns with useful values for as. Notice that both these fields are unique. So we can use them as Primary Key.

2021-01-24 15:54 UTC, ridisi95 commented on src/main/java/com/gulag/services/TournamentRegistrationService.java
> +    }
In this method we should only insert new record. if we try to insert value to column which already has the same value postgres returns a error and it's normal. This Error we should return in response.

2021-01-24 15:54 UTC, ridisi95 commented on src/main/java/com/gulag/services/TournamentRegistrationService.java
> +        return findById(tournament.get().getId()).isEmpty();
just return true

2021-01-24 15:54 UTC, ridisi95 commented on src/main/java/com/gulag/services/TournamentRegistrationDtoService.java
> +    @Autowired
You don't need to use @Autowired when you use @RequiredArgsConstructor.
You can check this https://www.baeldung.com/spring-injection-lombok

2021-01-24 21:28 UTC, RideSVEL commented on src/main/java/com/gulag/services/UserDtoService.java
> +        }
If I use Mapper UserDTO object`s not initialized.
![image](https://user-images.githubusercontent.com/55315596/105643967-cd2aad00-5e9b-11eb-8a4d-0c03c248bedf.png)

2021-01-25 20:50 UTC, ridisi95 approved these changes

2021-01-25 20:51 UTC, merged